### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by felox2** [felox2/webte2-final#2]
- [x] Prerobit databazu aby sa ulozil ziakov solution @felox2 
- [x] Pridat meno assigmentu pri vytvarani ucitelom, popis @felox2 
- [x] Kontrola studentovho riesenia @felox2 

### Žiak
- [x] Vidieť body za assigmenty
- [x] Vidieť ToDo a Done assigmenty
- [x] ToDo zobrazovať deadline
- [x] Po deadline zatvoriť ToDo test,
- [ ] ak si nevygeneroval tak si nemoze pozriet nic a dostane 0/x bodov(uvidi spravny vysledok az po deadline)
- [x] ak si vygeneroval tak si moze poriet priklady a aj ich riesenia
- [x] Po deadline vediet pozriet test aj s bodmi dole
- [x] Done assigment si vediet pozriet aj s riesenim studenta, spravnym riesenim, body
- [x] Vybrať si assigmenty 
- [x] Vygenerovať si 1 príklad a viac nie z danej sekcie
- [x] Vyriešiť assignmenty

### Učiteľ
- [x] Generovanie prikladov
- [x] Zadanie obdobia
- [x] ak nezadá tak od zadania do nekonečna
- [x] ak zadá tak od kedy do kedy zadal
- [ ] Latexové súbory
  - [x] zobraziť všetky v databáze
  - [ ] pridať
  - [ ] vymazať
  - [ ] (mozno pridat ak bude cas/pre lubosa) zobrazit priklady ktore su v danom latexe
  - [x] Prezerať tabuľku všetkých študentov
- [x] Prezerať u študenta
  - [x] vygenerované úlohy
  - [x] odovzdané úlohy
  - [x] odovzdaný výsledok + informáciu o správnosti
  - [x] získaný počet bodov za dané úlohy 

### Admin
- [x] upgrade študenta na učiteľa
- [x] mazanie žiakov a  učiteľov
- [ ] priame vytvorenie usera
- [ ] to isté čo učiteľ plus vyhľadanie aj učiteľov nie len študentov
